// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		403: typeof import('./components/ErrorMessage/403.vue')['default'];
		404: typeof import('./components/ErrorMessage/404.vue')['default'];
		500: typeof import('./components/ErrorMessage/500.vue')['default'];
		Doc: typeof import('./components/docs/doc.vue')['default'];
		ElAside: typeof import('element-plus/es')['ElAside'];
		ElButton: typeof import('element-plus/es')['ElButton'];
		ElColorPicker: typeof import('element-plus/es')['ElColorPicker'];
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
		ElContainer: typeof import('element-plus/es')['ElContainer'];
		ElDivider: typeof import('element-plus/es')['ElDivider'];
		ElDrawer: typeof import('element-plus/es')['ElDrawer'];
		ElFooter: typeof import('element-plus/es')['ElFooter'];
		ElForm: typeof import('element-plus/es')['ElForm'];
		ElFormItem: typeof import('element-plus/es')['ElFormItem'];
		ElHeader: typeof import('element-plus/es')['ElHeader'];
		ElIcon: typeof import('element-plus/es')['ElIcon'];
		ElImage: typeof import('element-plus/es')['ElImage'];
		ElInput: typeof import('element-plus/es')['ElInput'];
		ElMain: typeof import('element-plus/es')['ElMain'];
		ElMenu: typeof import('element-plus/es')['ElMenu'];
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
		ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
		ElSwitch: typeof import('element-plus/es')['ElSwitch'];
		ElTooltip: typeof import('element-plus/es')['ElTooltip'];
		Font: typeof import('./components/docs/font.vue')['default'];
		Highlight: typeof import('./components/docs/highlight.vue')['default'];
		Loading: typeof import('./components/Loading/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
		SwitchDark: typeof import('./components/SwitchDark/index.vue')['default'];
	}
}
